#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
cd $OPENSHIFT_REPO_DIR/spray-template
nohup java -jar target/scala-2.10/spray-template-fat.jar > $OPENSHIFT_DIY_DIR/logs/server.log 2>&1 &
